import type { GlobalThemeOverrides } from "naive-ui";

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: "#1E4B8C",
    primaryColorHover: "#2A5FA8",
    primaryColorPressed: "#153A6E",
    primaryColorSuppl: "#2A5FA8",
    infoColor: "#3B6EA5",
    successColor: "#15803D",
    warningColor: "#C2740A",
    errorColor: "#B91C1C",
    textColorBase: "#0F172A",
    textColor1: "#0F172A",
    textColor2: "#334155",
    textColor3: "#64748B",
    borderColor: "#E2E8F0",
    dividerColor: "#E2E8F0",
    bodyColor: "#F7F9FB",
    cardColor: "#FFFFFF",
    fontFamily: '"IBM Plex Sans", -apple-system, "Segoe UI", sans-serif',
    fontFamilyMono: '"IBM Plex Mono", "SF Mono", Consolas, monospace',
    borderRadius: "6px",
    borderRadiusSmall: "4px",
    heightMedium: "34px",
  },
  DataTable: {
    thColor: "#F7F9FB",
    thTextColor: "#64748B",
    thFontWeight: "600",
    tdColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    thPaddingMedium: "8px 12px",
    tdPaddingMedium: "8px 12px",
  },
  Button: { fontWeight: "500" },
  Card: { borderRadius: "8px", borderColor: "#E2E8F0" },
  Tag: { borderRadius: "4px" },
  Menu: {
    itemColorActive: "rgba(255,255,255,0.08)",
    itemTextColorActive: "#FFFFFF",
    itemIconColorActive: "#FFFFFF",
  },
};
